// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// create
type CreateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateReq) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type CreateResp struct {
	Code                 int64           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *CreateRespData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (m *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(m, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateResp) GetData() *CreateRespData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRespData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRespData) Reset()         { *m = CreateRespData{} }
func (m *CreateRespData) String() string { return proto.CompactTextString(m) }
func (*CreateRespData) ProtoMessage()    {}
func (*CreateRespData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateRespData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRespData.Unmarshal(m, b)
}
func (m *CreateRespData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRespData.Marshal(b, m, deterministic)
}
func (m *CreateRespData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRespData.Merge(m, src)
}
func (m *CreateRespData) XXX_Size() int {
	return xxx_messageInfo_CreateRespData.Size(m)
}
func (m *CreateRespData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRespData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRespData proto.InternalMessageInfo

func (m *CreateRespData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRespData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRespData) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

// Delete
type DeleteReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResp struct {
	Code                 int64           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *DeleteRespData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (m *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(m, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

func (m *DeleteResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DeleteResp) GetData() *DeleteRespData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRespData struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRespData) Reset()         { *m = DeleteRespData{} }
func (m *DeleteRespData) String() string { return proto.CompactTextString(m) }
func (*DeleteRespData) ProtoMessage()    {}
func (*DeleteRespData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *DeleteRespData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRespData.Unmarshal(m, b)
}
func (m *DeleteRespData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRespData.Marshal(b, m, deterministic)
}
func (m *DeleteRespData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRespData.Merge(m, src)
}
func (m *DeleteRespData) XXX_Size() int {
	return xxx_messageInfo_DeleteRespData.Size(m)
}
func (m *DeleteRespData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRespData.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRespData proto.InternalMessageInfo

func (m *DeleteRespData) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CreateReq)(nil), "pb.CreateReq")
	proto.RegisterType((*CreateResp)(nil), "pb.CreateResp")
	proto.RegisterType((*CreateRespData)(nil), "pb.CreateRespData")
	proto.RegisterType((*DeleteReq)(nil), "pb.DeleteReq")
	proto.RegisterType((*DeleteResp)(nil), "pb.DeleteResp")
	proto.RegisterType((*DeleteRespData)(nil), "pb.DeleteRespData")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xb2, 0x2c, 0x66, 0x84, 0x22, 0x73, 0x90, 0x1e, 0x4b, 0x0f, 0x92, 0x53, 0x45,
	0x7d, 0x04, 0x17, 0x1f, 0x20, 0x47, 0x6f, 0xa9, 0x19, 0x4a, 0xa1, 0xb5, 0x31, 0x49, 0xdf, 0x5f,
	0x92, 0xb6, 0xd6, 0x22, 0x9e, 0xf6, 0xf6, 0x67, 0xc2, 0x37, 0xf9, 0x3f, 0x02, 0x30, 0x07, 0xf2,
	0x8d, 0xf3, 0x53, 0x9c, 0x90, 0xbb, 0xb6, 0x7e, 0x02, 0xf9, 0xea, 0xc9, 0x44, 0xd2, 0xf4, 0x85,
	0x08, 0xa7, 0x4f, 0x33, 0x52, 0xc9, 0x2a, 0xa6, 0xa4, 0xce, 0x19, 0xef, 0x40, 0x98, 0x8e, 0x4a,
	0x5e, 0x31, 0x25, 0x74, 0x8a, 0xf5, 0x3b, 0xc0, 0x86, 0x04, 0x97, 0x98, 0x8f, 0xc9, 0x2e, 0x8c,
	0xd0, 0x39, 0x27, 0x66, 0x0c, 0x5d, 0x66, 0xa4, 0x4e, 0x11, 0x1f, 0xe0, 0x64, 0x4d, 0x34, 0xa5,
	0xa8, 0x98, 0xba, 0x7d, 0xc6, 0xc6, 0xb5, 0xcd, 0xbe, 0xe3, 0x62, 0xa2, 0xd1, 0xf9, 0xbe, 0x7e,
	0x83, 0xe2, 0x38, 0xc7, 0x02, 0x78, 0x6f, 0xd7, 0x46, 0xbc, 0xb7, 0x3f, 0x1d, 0xf9, 0xdf, 0x8e,
	0x62, 0xef, 0xf8, 0x08, 0xf2, 0x42, 0x03, 0xfd, 0xaf, 0xb5, 0xac, 0x5d, 0xac, 0x78, 0x6f, 0x93,
	0xd4, 0x06, 0x5c, 0x23, 0xb5, 0xef, 0xf8, 0x25, 0xa5, 0xa0, 0x38, 0xce, 0xf1, 0x1e, 0xce, 0x9e,
	0xc2, 0x3c, 0xc4, 0xfc, 0xc2, 0x8d, 0x5e, 0x4f, 0xed, 0x39, 0x7f, 0xcc, 0xcb, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x41, 0x7d, 0x01, 0xb4, 0xa6, 0x01, 0x00, 0x00,
}
